# SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: setup policyctl
author: carabiner-dev
description: 'Installs the Carabiner policyctl AMPEL policy manager to the runner environment'
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
  version:
    description: 'policyctl version to install'
    required: false
    default: 'v0.1.0'
runs:
  using: "composite"
  steps:
    - uses: carabiner-dev/actions/install/download-and-verify@2a11d59a135c5e291f305f249a92ad7903e3ee0f # v1.1.7
      with:
        tool: policyctl
        version: ${{ inputs.version }}
        install-dir: ${{ inputs.install-dir }}
        attestation-file: policyctl-${{ inputs.version }}.provenance.json
