# SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
# SPDX-License-Identifier: Apache-2.0

name: setup ampel
author: carabiner-dev
description: "Installs the \U0001F534\U0001F7E1\U0001F7E2 AMPEL policy engine into to the runner environment"
branding:
  icon: 'download-cloud'
  color: 'green'
inputs:
  install-dir:
    description: 'Path to install the binary'
    required: false
    default: '$HOME/.carabiner'
  version:
    description: 'AMPEL Version to Install'
    required: false
    default: 'v1.2.1'
runs:
  using: "composite"
  steps:
    - uses: carabiner-dev/actions/install/download-and-verify@e0e3b8149dafed833431095bc148d50e7eade4e8 # v1.2.0
      with:
        tool: ampel
        version: ${{ inputs.version }}
        install-dir: ${{ inputs.install-dir }}
        attestation-file: ampel-${{ inputs.version }}.provenance.json
